name: 'Full Build'
on:
    release:
        types: [created]

jobs:
    add-dependencies:
        name: 'Setup Dependencies'
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: 'Build'
              run: |
                  npm i
                  npm run build:releases

            - name: 'Generate Checksums'
              run: |
                  sha256sum ./releases/contract-builder-win.exe > ./releases/windows-checksum.txt
                  sha256sum ./releases/contract-builder-linux > ./releases/linux-checksum.txt
                  sha256sum ./releases/contract-builder-macos > ./releases/macos-checksum.txt

            - name: Get package version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Create release and add files
              uses: softprops/action-gh-release@v1
              with:
                  name: Release ${{ steps.package-version.outputs.current-version }}
                  tag_name: ${{ steps.package-version.outputs.current-version }}
                  files: ./releases/*
